# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (fasta|pdb|cif|mds|json)$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    exclude: pixi.lock
  - id: check-merge-conflict
- repo: https://github.com/seddonym/import-linter
  rev: v1.12.1
  hooks:
  - id: import-linter
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.3
  hooks:
  - id: ruff # linter
    args: [ --fix ]
  - id: ruff-format # formatter
    types_or: [python, jupyter]
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.399
  hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: system
      types: [python]
      pass_filenames: true # For speed, we only check the files that are changed
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks
